# Generated by Django 4.2.6 on 2024-01-22 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="contratos",
            fields=[
                (
                    "Numero_Contrato",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("Asesor", models.CharField(max_length=50)),
                ("valor", models.IntegerField()),
                ("descripcion", models.CharField(max_length=255)),
                ("Fecha_Inicial", models.DateTimeField(auto_now_add=True)),
                ("Fecha_Final", models.DateTimeField()),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CarteraApp.clientes",
                    ),
                ),
            ],
        ),
    ]
