# Generated by Django 4.2.6 on 2024-01-22 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0002_contratos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contratos",
            old_name="Asesor",
            new_name="asesor",
        ),
    ]
