# Generated by Django 4.2.6 on 2024-01-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0003_rename_asesor_contratos_asesor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratos",
            name="Fecha_Final",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="contratos",
            name="Fecha_Inicial",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="contratos",
            name="Numero_Contrato",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
