# Generated by Django 4.2.6 on 2024-01-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0004_alter_contratos_fecha_final_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratos",
            name="Fecha_Final",
            field=models.DateField(blank=True, null=True),
        ),
    ]
