# Generated by Django 4.2.6 on 2024-01-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0005_alter_contratos_fecha_final"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratos",
            name="archivo_contrato",
            field=models.FileField(blank=True, null=True, upload_to="contratos/"),
        ),
    ]
