# Generated by Django 4.2.6 on 2024-01-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0006_contratos_archivo_contrato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratos",
            name="archivo_contrato",
            field=models.FileField(upload_to="contratos/"),
        ),
    ]
