# Generated by Django 4.2.6 on 2024-01-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0007_alter_contratos_archivo_contrato"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pagos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_pago",
                    models.CharField(
                        choices=[
                            ("recibo_de_caja", "Recibo de Caja"),
                            ("factura", "Factura"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "numero_contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CarteraApp.contratos",
                    ),
                ),
            ],
        ),
    ]
