# Generated by Django 4.2.6 on 2024-01-23 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0008_pagos"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pagos",
        ),
    ]
