# Generated by Django 4.2.6 on 2024-01-23 15:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0009_delete_pagos"),
    ]

    operations = [
        migrations.CreateModel(
            name="pagos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_pago",
                    models.CharField(
                        choices=[
                            ("recibo_de_caja", "Recibo de Caja"),
                            ("factura", "Factura"),
                        ],
                        max_length=20,
                    ),
                ),
                ("valor_pago", models.IntegerField()),
                (
                    "fecha_pago",
                    models.DateField(
                        default=datetime.datetime(2024, 1, 23, 10, 44, 39, 964109)
                    ),
                ),
                ("archivo_pago", models.FileField(upload_to="Recibos/")),
                (
                    "numero_contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="CarteraApp.contratos",
                    ),
                ),
            ],
        ),
    ]
