# Generated by Django 4.2.6 on 2024-01-23 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0010_pagos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagos",
            name="fecha_pago",
            field=models.DateField(
                default=datetime.datetime(2024, 1, 23, 10, 44, 55, 847318)
            ),
        ),
    ]
