# Generated by Django 4.2.6 on 2024-01-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0011_alter_pagos_fecha_pago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagos",
            name="fecha_pago",
            field=models.DateField(),
        ),
    ]
