# Generated by Django 4.2.6 on 2024-01-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0012_alter_pagos_fecha_pago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagos",
            name="archivo_pago",
            field=models.FileField(blank=True, null=True, upload_to="Recibos/"),
        ),
    ]
