# Generated by Django 4.2.6 on 2024-01-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0015_alter_contratos_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratos",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
