# Generated by Django 5.0.2 on 2024-02-20 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0018_alter_contratos_archivo_contrato"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contratos",
            old_name="Fecha_Final",
            new_name="fecha_final",
        ),
        migrations.RenameField(
            model_name="contratos",
            old_name="Fecha_Inicial",
            new_name="fecha_inicial",
        ),
        migrations.RenameField(
            model_name="contratos",
            old_name="Numero_Contrato",
            new_name="numero_contrato",
        ),
    ]
