# Generated by Django 4.1 on 2024-03-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0019_rename_fecha_final_contratos_fecha_final_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratos",
            name="fecha_final",
            field=models.DateField(),
        ),
    ]
