# Generated by Django 4.1 on 2024-03-04 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0020_alter_contratos_fecha_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratos",
            name="fecha_final",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
