# Generated by Django 4.1 on 2024-03-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0021_alter_contratos_fecha_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratos",
            name="fecha_final",
            field=models.DateField(),
        ),
    ]
