# Generated by Django 4.1 on 2024-03-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0022_alter_contratos_fecha_final"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagos",
            name="archivo_pago",
            field=models.FileField(upload_to="Recibos/"),
        ),
    ]
