# Generated by Django 4.1 on 2024-03-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0023_alter_pagos_archivo_pago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagos",
            name="tipo_pago",
            field=models.CharField(
                choices=[
                    ("recibo_de_caja_efectivo", "Recibo de caja - Efectivo"),
                    ("recibo_de_caja_banco", "Recibo de caja -  Banco"),
                    ("abono", " Abono"),
                ],
                max_length=50,
            ),
        ),
    ]
