# Generated by Django 4.2.11 on 2024-04-16 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0024_alter_pagos_tipo_pago"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagos",
            old_name="numero_contrato",
            new_name="contrato",
        ),
    ]
