# Generated by Django 4.2.11 on 2024-04-16 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0025_rename_numero_contrato_pagos_contrato"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdicionContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nuevo_valor", models.IntegerField(blank=True, null=True)),
                ("nueva_fecha", models.DateField(blank=True, null=True)),
                ("archivo_nuevo", models.FileField(upload_to="contratos/")),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="CarteraApp.contratos",
                    ),
                ),
            ],
        ),
    ]
