# Generated by Django 4.2.11 on 2024-04-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CarteraApp", "0026_adicioncontrato"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratos",
            name="valor_subcontratos",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
